### ISSUE TITLE
Annotations - Enable storage of the method that was used to determine a parameter

### ISSUE THREAD

**Issue by srjimenez** [BlueBrain/neurocurator#59]
- The method used to determine a parameter is important to keep.
- For example: Neuronal Density Method: was calculated by applying the method of Weibel and
Gomez

**Comment by pafonta** [comment]
Require discussions with @christian-oreilly.

**Comment by christian-oreilly** [comment]
Adding high level information on the method can be done by adding an ontological term as a tag (e.g., adding a "Cavalieri method" tag to an annotation). From the user point of view, this mainly requires them to be able to add new "ontological terms" (here, more accurately, they are treated as controlled vocabulary) to be able to use them in tagging, since most of the required terms are not likely to be already covered by NIFSTD. This relates to issue #13. The design of a support for more structured information on the experimental protocol is currently out of the scope of this project, not because it would not be beneficial to the quality of the annotations, but because it is unlikely that the annotators will want to support this overhead in their annotation process.

**Comment by pafonta** [comment]
Solution (from Christian's comment):

> Adding high level information on the method can be done by adding an ontological term as a tag (e.g., adding a "Cavalieri method" tag to an annotation).

Reason (idem):

> The design of a support for more structured information on the experimental protocol is currently out of the scope of this project [...].

I therefore close this issue.
