### ISSUE TITLE
Annotation - enable the capacity to add a "coefficient of error" under "statistics"

### ISSUE THREAD

**Issue by srjimenez** [BlueBrain/neurocurator#66]
For the annotation of statistical results from tables either as point values, numerical trace...:
Please enable the annotation of the "coefficient of error" under "statistic" where it is not available.
The coefficient of error is a standard statistical value that is used extensively in the stereological literature. 
The definition :  It is defined as the standard error of the mean of repeated estimates divided by the mean.

![image](https://user-images.githubusercontent.com/16578898/34950783-6bbfcfee-fa14-11e7-9a84-ec78717b430e.png)

**Comment by pafonta** [comment]
@christian-oreilly Please validate (+1 on original post) or invalidate (-1 on original post) if not done for a reason.

**Comment by christian-oreilly** [comment]
In this case, the "coefficient of error" does not appear to be a standard statistics that is field-independent. I seems to be a variable specifically developed and used in the context of stereology. For example, for the use-case at hand, it is used in table 1 (CE) of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2100216/ and it is defined in details in the section "Statistical Analysis". As such, it would be modeled more as a separate "modeling parameter" than as a supplementary statistics of a given parameter (i.e., neuron count). 

On a side note, this highlights the need to eventually be able to cross-reference parameters and/or annotations beyond the use of the "experimental property" mechanism, because we see here that we are limited in our possibility to encode the fact that the coefficient of error parameter is linked in some conceptual and mathematical way to the neuron count. But that would be the topic of a separate ticket.

For the specific request, and for the reasons explained above: -1

**Comment by pafonta** [comment]
Tagged _won't fix_ and closed because:

> the "coefficient of error" does not appear to be a standard statistics that is field-independent

and

> it would be modeled more as a separate "modeling parameter" than as a supplementary statistics of a given parameter

**Comment by srjimenez** [comment]
The "coefficient of error" IS field-independent. It is the standard error of the mean of repeated estimates divided by the mean.
The fact that it is commonly used in Stereology doesn't mean that it is uniquely used there.

**Comment by christian-oreilly** [comment]
For the record, here are some arguments that support my previous statement:

First: Googling "coefficient of error" gives the following web pages at top 3:
www.stereology.info/coefficient-of-error/
www.stereology.info/some-ce-theory/
www.mbfbioscience.com/help/si11/Content/SI.../Coefficient_of_Error.htm
All are related to stereology.

The fourth listed web site (https://encyclopedia2.thefreedictionary.com/error+coefficient) gives a definition unrelated to what has to be annotated here, but related to the field of control system : "The steady-state value of the output of a control system, or of some derivative of the output, divided by the steady-state actuating signal. Also known as error constant." 

Second, the "coefficient of error" in the annotated paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2100216/ is defined in the "Statistical Analysis" section of this paper, which cites relatively **recent** papers in **stereology**. Thus, this measure is not an established standard and field-independent statistics. 

Third, there is no mention of "coefficient of error" in well-know field-independent resources like Wikipedia. It is not even well known enough for it to have its stereology-related definition given there.

To support the claim that it is field-independent, we would need to provide an authoritative reference defining this mathematical construct in a text that is not dependent on the field of application (e.g., a statistics handbook).

The reason why not to add a "statistics" for every field-related idiosyncratic mathematical definition is that, if we were to do so, this list would grow much too large and would be filled of "statistics" which definition is not well know or easy to find, which are only used for rare and field-specific annotations, and which meaning is confusing (e.g., the definition of "coefficient of error" from stereology, versus the one in control system, versus the one in other fields). 

Conclusion: Adding it to the list of "statistics" is not the proper mechanism to model this information.
