### ISSUE TITLE
[Annotations] Adding locally a PDF for a reference with existing annotations delete them

### ISSUE THREAD

**Issue by christian-oreilly** [BlueBrain/neurocurator#76]
Steps:

1. Find a paper which has a remote PDF but no local PDF (i.e., grey rows) and which has annotations.
2. Add a local PDF.
3. Look and rejoice in the disappearance of previously curated material. 

This bug was tested with the paper with DOI 10.1073/pnas.1312691110

**Comment by pafonta** [comment]
Notes:

- There is no corresponding stack trace.
- The deletion can be shown with `git diff HEAD^ HEAD` in the folder where the annotations are.

**Comment by pafonta** [comment]
@christian-oreilly I found the reason.

There is no check if there is already a PCR file when importing a PDF...

This have been there since 2nd August 2016 (commit https://github.com/BlueBrain/neurocurator/commit/5b67f3a40d9ebd0e44d015a178908bdc48879507).

We should check in the git history if there has been data loss...

See https://github.com/BlueBrain/neurocurator/blob/1a49686b9ae44f1a8858b61af02cf98ba4a33bbd/neurocurator/mainWin.py#L1143
